<?php







if (!getActiveUsers()) {



    $giris = getLangValue(25);



    redirect(base_url(gg() . $giris->link));



} else {



    $user = getActiveUsers();



    $uniql = getLangValue($uniq->id, "table_pages");



}



?>



<style>



    .heartbeat {



        -webkit-animation: heartbeat 1.5s ease-in-out infinite both;



        animation: heartbeat 1.5s ease-in-out infinite both;



    }







    /* ----------------------------------------------



 * Generated by Animista on 2023-11-30 1:2:28



 * Licensed under FreeBSD License.



 * See http://animista.net/license for more info.



 * w: http://animista.net, t: @cssanimista



 * ---------------------------------------------- */







    /**



     * ----------------------------------------



     * animation heartbeat



     * ----------------------------------------



     */



    @-webkit-keyframes heartbeat {



        from {



            -webkit-transform: scale(1);



            transform: scale(1);



            -webkit-transform-origin: center center;



            transform-origin: center center;



            -webkit-animation-timing-function: ease-out;



            animation-timing-function: ease-out;



        }







        10% {



            -webkit-transform: scale(0.91);



            transform: scale(0.91);



            -webkit-animation-timing-function: ease-in;



            animation-timing-function: ease-in;



        }







        17% {



            -webkit-transform: scale(0.98);



            transform: scale(0.98);



            -webkit-animation-timing-function: ease-out;



            animation-timing-function: ease-out;



        }







        33% {



            -webkit-transform: scale(0.87);



            transform: scale(0.87);



            -webkit-animation-timing-function: ease-in;



            animation-timing-function: ease-in;



        }







        45% {



            -webkit-transform: scale(1);



            transform: scale(1);



            -webkit-animation-timing-function: ease-out;



            animation-timing-function: ease-out;



        }



    }







    @keyframes heartbeat {



        from {



            -webkit-transform: scale(1);



            transform: scale(1);



            -webkit-transform-origin: center center;



            transform-origin: center center;



            -webkit-animation-timing-function: ease-out;



            animation-timing-function: ease-out;



        }







        10% {



            -webkit-transform: scale(0.91);



            transform: scale(0.91);



            -webkit-animation-timing-function: ease-in;



            animation-timing-function: ease-in;



        }







        17% {



            -webkit-transform: scale(0.98);



            transform: scale(0.98);



            -webkit-animation-timing-function: ease-out;



            animation-timing-function: ease-out;



        }







        33% {



            -webkit-transform: scale(0.87);



            transform: scale(0.87);



            -webkit-animation-timing-function: ease-in;



            animation-timing-function: ease-in;



        }







        45% {



            -webkit-transform: scale(1);



            transform: scale(1);



            -webkit-animation-timing-function: ease-out;



            animation-timing-function: ease-out;



        }



    }







    @media screen and (max-width: 800px) {



        .left-nav .nav.nav-tabs button {



            height: max-content;



            border: none;



            color: var(--color-white);



            padding: 5px 5px !important;



            position: relative;



            margin: 6px;



            border-radius: 6px;



            border: 1px dashed var(--color-border);



            transition: 0.4s;



            display: inline-block;



            text-align: left;



            transition: var(--transition);



            line-height: 22px;



            outline: none;



        }



    }



</style>











<div class="rn-breadcrumb-inner ptb--30 css-selector">



    <div class="container">



        <div class="row align-items-center">



            <div class="col-lg-6 col-md-6 col-12">



                <?php



                if ($page->id == 99) {



                    $uniql = getLangValue($page->id, "table_pages");



                ?>



                    <h5 class="title text-center text-md-start"><?= langS(267) ?> - <?= $uniql->titleh1 ?> - #<?= $items->islemNo ?></h5>



                <?php



                } else {



                ?>



                    <h5 class="title text-center text-md-start"><?= langS(267) ?> - <?= $uniql->titleh1 ?></h5>



                <?php



                }



                ?>







            </div>



            <?php



            $bakiye = getLangValue(28, "table_pages");







            $ilanolustur = getLangValue(29, "table_pages");







            $cekim = getLangValue(51, "table_pages");







            if (getActiveUsers()) {



                $userr = getActiveUsers();



            ?>



                <div class="col-lg-6 col-md-6 col-12 " style="position:relative;">







                    <div class="author-button-area  mt-4 d-flex align-items-center justify-content-end   " style="margin: 0; padding:0">



                        <a href="<?= base_url(gg() . $bakiye->link) ?>" class="btn at-follw brebutton  share-button">



                            <img width="20px" src="<?= base_url("assets/images/icom/purse.png") ?>"> <?= ($_SESSION["lang"] == 1) ? "Bakiye Yükle" : "Balance Add" ?>



                        </a>

                        <?php



                        if ($userr->is_magaza == 1) {



                        ?>



                            <a href="<?= base_url(gg() . $cekim->link) ?>" class="btn brebutton at-follw  share-button">



                                <img width="20px" src="<?= base_url("assets/img/icon/cash-on-delivery.png") ?>"> <?= ($_SESSION["lang"] == 1) ? "Nakit Çek" : "Balance With" ?>



                            </a>



                            <a href="<?= base_url(gg() . $ilanolustur->link) ?>" class="btn brebutton  at-follw  share-button">



                                <img width="20px" src="<?= base_url("assets/img/game.png") ?>"> <?= ($_SESSION["lang"] == 1) ? "İlan Oluştur" : "Add Product" ?>



                            </a>







                        <?php



                        }



                        ?>







                    </div>



                </div>



            <?php



            }



            ?>



        </div>



    </div>



</div>







<div class="edit-profile-area pt--40">



    <div class="container">



        <div class="row mb-5 padding-control-edit-wrapper pl_md--0 pr_md--0 pl_sm--0 pr_sm--0">



            <div class="col-lg-12">



                <div class="category-area ">



                    <div class="row">



                        <div class="col-lg-3 col-6 col-xl-2 col-md-4 col-sm-6  col-md-4 col-sm-6 mb-3" style="">



                            <a rel="preload" class="category-style-one uyeBild" href="javascript:;">



                                <img width="40" src="<?= base_url() ?>assets/images/icom/purse.png" alt="">



                                <span style="font-size: 13px" class="category-label"><?= langS(28) ?>: <b><?= number_format($user->balance, 2) . " " . getcur() ?></b></span></a>



                        </div>



                        <div class="col-lg-3 col-6 col-xl-2 col-md-4 col-sm-6  col-md-4 col-sm-6 mb-3" style="padding-left: 5px; padding-right: 5px">



                            <a rel="preload" class="category-style-one uyeBild" href="javascript:;">



                                <img width="40" src="<?= base_url() ?>assets/images/icom/wallet.png" alt="">



                                <span style="font-size: 13px" class="category-label"><?= langS(29) ?>: <b><?= number_format(getActiveUsers()->ilan_balance, 2) . " " . getcur() ?></b></span></a>



                        </div>



                        <?php



                        $mesaj = getLangValue(38, "table_pages");



                        ?>



                        <div class="col-lg-3 col-6 col-xl-2 col-md-4 col-sm-6  col-md-4 col-sm-6 mb-3" style="">



                            <a rel="preload" class="category-style-one uyeBild" href="<?= base_url(gg() . $mesaj->link) ?>">



                                <img width="40" src="<?= base_url() ?>assets/images/icom/messages.png" alt="">



                                <span style="font-size: 13px" class="category-label"><?= langS(32) ?>: <b>



                                        <?php



                                        $cr = $this->m_tr_model->query("select * from table_users_message_gr where (user_id=" . $user->id . " or seller_id=" . $user->id . ") ");



                                        if ($cr) {



                                            foreach ($cr as $item) {



                                                if ($item->seller_id == $user->id) {



                                                    //Mağaza giriş yapmış



                                                    $crs = $this->m_tr_model->query("select count(*) as say from table_users_message where seller_id=" . $user->id . " and islemNo='" . $item->islemNo . "' and type=0 and is_read=0");



                                                    if ($crs) {



                                                        if ($crs[0]->say > 0) {



                                                            $toplam += $crs[0]->say;



                                                        }



                                                    }



                                                } else {



                                                    // Üye Giriş yapmış



                                                    $crs = $this->m_tr_model->query("select count(*) as say from table_users_message where user_id=" . $user->id . " and islemNo='" . $item->islemNo . "' and type=1 and is_read=0");



                                                    if ($crs) {



                                                        if ($crs[0]->say > 0) {



                                                            $toplam += $crs[0]->say;



                                                        }



                                                    }



                                                }



                                            }



                                        }



                                        echo $toplam;



                                        $satislars = getLangValue(57, "table_pages");



                                        ?>







                                    </b></span></a>



                        </div>



                        <div class="col-lg-3 col-6 col-xl-2 col-md-4 col-sm-6  col-md-4 col-sm-6 mb-3" style="padding-left: 5px; padding-right: 5px">



                            <a rel="preload" class="category-style-one uyeBild" href="<?= base_url(gg() . $satislars->link)  ?>">



                                <img width="40" src="<?= base_url() ?>assets/images/icom/received.png" alt="">



                                <span style="font-size: 13px" class="category-label"><?= langS(33) ?>: <b>



                                        <?php











                                        $satislar = getTable("table_orders_adverts", array("sell_user_id" => getActiveUsers()->id, "status" => 0));



                                        if ($satislar) {



                                            if (count($satislar) > 0) {



                                        ?>



                                                <span class="bg-warning heartbeat" style="line-height:20px;display:inline-block;border-radius: 50%; width: 20px; height:20px;color:black;text-align: center">1</span>



                                        <?php



                                            }



                                        } else {



                                            echo "-";



                                        }



                                        ?>



                                    </b></span></a>



                        </div>



                        <div class="col-lg-3 col-6  col-xl-2 col-md-4 col-sm-6  col-md-4 col-sm-6 mb-3" style="">



                            <a rel="preload" class="category-style-one uyeBild" href="javascript:;">



                                <img width="40" src="<?= base_url() ?>assets/images/icom/wage.png" alt="">



                                <?php



                                $harcama1 = $this->m_tr_model->query("select sum(total_price) as say from table_orders where user_id=" . getActiveUsers()->id . " and status=2 ");



                                $harcama2 = $this->m_tr_model->query("select sum(price_total) as say from table_orders_adverts where user_id=" . getActiveUsers()->id . " and status=3 ");



                                $vas = $this->m_tr_model->query("select sum(cash_price) as say from table_users_ads_cash where user_id=" . getActiveUsers()->id . " and is_blocked=0 ");



                                if ($vas) {



                                    if ($vas[0]->say > 0) {



                                ?>



                                        <span style="font-size: 13px" class="category-label"><?= langS(34) ?>: <b><?= custom_number_format($vas[0]->say) . " " . getcur() ?></b></span></a>



                        <?php



                                    } else {



                        ?>



                            <span style="font-size: 13px" class="category-label"><?= langS(34) ?>: <b>-</b></span></a>







                        <?php



                                    }



                                } else {



                        ?>



                        <span style="font-size: 13px" class="category-label"><?= langS(34) ?>: <b>-</b></span></a>







                    <?php



                                }



                    ?>



                        </div>



                        <div class="col-lg-3  col-6 col-xl-2 col-md-4 col-sm-6  col-md-4 col-sm-6 " style="padding-left: 5px; padding-right: 5px">



                            <a rel="preload" class="category-style-one uyeBild" href="javascript:;">



                                <img width="40" src="<?= base_url() ?>assets/images/icom/spend.png" alt="">



                                <span style="font-size: 13px" class="category-label"><?= langS(35) ?>: <b>



                                        <?php



                                        $topla = 0;



                                        if ($harcama1) {



                                            if ($harcama1[0]->say > 0) {



                                                $topla += $harcama1[0]->say;



                                            }



                                        }



                                        if ($harcama2) {



                                            if ($harcama2[0]->say > 0) {



                                                $topla += $harcama2[0]->say;



                                            }



                                        }



                                        ?>







                                        <?= number_format($topla, 2) . " " . getcur() ?></b></span></a>



                        </div>







                    </div>



                </div>



            </div>



        </div>



        <div class="row  padding-control-edit-wrapper pl_md--0 pr_md--0 pl_sm--0 pr_sm--0">



            <div class="col-lg-2 col-md-3 col-sm-12">



                <!-- Start tabs area -->



                <nav class="left-nav rbt-sticky-top-adjust-five" style="padding-right: 0px !important;">



                    <div class="nav nav-tabs" id="nav-tab" role="tablist">



                        <?php



                        $magaza = getLangValue(95, "table_pages");



                        $sifre = getLangValue(49, "table_pages");



                        $ilanlarim = getLangValue(36, "table_pages");



                        $destek = getLangValue(97, "table_pages");



                        $takip = getLangValue(98, "table_pages");



                        $bildirim = getLangValue(78, "table_pages");



                        $dogrulama = getLangValue(42, "table_pages");



                        $ilansiparisler = getLangValue(54, "table_pages");



                        $ayarlar = getLangValue(37, "table_pages");



                        $mesaj = getLangValue(38, "table_pages");



                        $satislar = getLangValue(57, "table_pages");



                        $siparisler = getLangValue(43, "table_pages");



                        $kasaGecmisim = getLangValue(119, "table_pages");

                        

                        $bakiyeIade = getLangValue(120, "table_pages");



                        $faturaBilgileri = getLangValue(121, "table_pages");



                        $yayinciPaneli = getLangValue(122, "table_pages");



                        $bagisGecmisi = getLangValue(124,"table_pages");



                        $bizeSatSiparisler = getLangValue(125, "table_pages");



                        $cekilisSistemi = getLangValue(128, "table_pages");



                        $referansSistemi = getLangValue(129, "table_pages");

                        ?>



                        <button  onclick="git('<?= base_url(gg() . $faturaBilgileri->link) ?>#content')" class="nav-link <?= ($uniq->id == 121) ? "active" : "" ?>">



                            <img width="26px" style="margin-right: 10px;" src="<?= b() . "assets/images/edit.png" ?>"><?= $faturaBilgileri->titleh1 ?>



                        </button>

                        <button  onclick="git('<?= base_url(gg() . $siparisler->link) ?>#content')" class="nav-link <?= ($uniq->id == 43) ? "active" : "" ?>">



                            <img width="26px" style="margin-right: 10px;" src="<?= b() . "assets/img/icon/received.png" ?>"><?= $siparisler->titleh1 ?>



                        </button>

                        <button  onclick="git('<?= base_url(gg() . $bizeSatSiparisler->link) ?>#content')" class="nav-link <?= ($uniq->id == 125) ? "active" : "" ?>">



                            <img width="26px" style="margin-right: 10px;" src="<?= b() . "assets/img/icon/received.png" ?>"><?= $bizeSatSiparisler->titleh1 ?>



                        </button>



                        <button onclick="git('<?= base_url(gg() . $ilansiparisler->link) ?>#content')" class="nav-link <?= ($uniq->id == 54) ? "active" : "" ?>">



                            <img width="26px" style="margin-right: 10px;" src="<?= b() . "assets/img/icon/order.png" ?>"><?= $ilansiparisler->titleh1 ?>



                        </button>

                        

                        <button onclick="git('<?= base_url(gg() . $kasaGecmisim->link) ?>#content')" class="nav-link <?= ($uniq->id == 119) ? "active" : "" ?>">



                            <img width="26px" style="margin-right: 10px;" src="<?= b() . "upload/icon/open-box.png" ?>"><?= $kasaGecmisim->titleh1 ?>



                        </button>

                        <?php



                        if (getActiveUsers()->is_magaza == 1) {



                        ?>



                            <button onclick="git('<?= base_url(gg() . $magaza->link) ?>#content')" class="nav-link <?= ($uniq->id == 95) ? "active" : "" ?>">



                                <img width="26px" style="margin-right: 10px;" src="<?= b() . "assets/img/shop.png" ?>"><?= langS(66) ?>



                            </button>



                            <button onclick="git('<?= base_url(gg() . $ilanolustur->link) ?>#content')" class="nav-link <?= ($uniq->id == 29) ? "active" : "" ?>">



                                <img width="26px" style="margin-right: 10px;" src="<?= b() . "assets/img/game.png" ?>"><?= $ilanolustur->titleh1 ?>



                            </button>



                            <button onclick="git('<?= base_url(gg() . $ilanlarim->link) ?>#content')" class="nav-link <?= ($uniq->id == 36) ? "active" : "" ?>">



                                <img width="26px" style="margin-right: 10px;" src="<?= b() . "assets/img/loading.png" ?>"><?= $ilanlarim->titleh1 ?>



                            </button>



                            <button onclick="git('<?= base_url(gg() . $satislar->link) ?>#content')" role="link" class="nav-link <?= ($uniq->id == 57) ? "active" : "" ?>">



                                <img width="26px" style="margin-right: 10px;" src="<?= b() . "upload/icon/open-box.png" ?>"><?= $satislar->titleh1 ?>



                                <?php



                                $satislar = getTable("table_orders_adverts", array("sell_user_id" => getActiveUsers()->id, "status" => 0));



                                if ($satislar) {



                                    if (count($satislar) > 0) {



                                ?>



                                        <span class="bg-warning heartbeat" style="line-height:20px;display:inline-block;border-radius: 50%; width: 20px; height:20px;color:black;text-align: center">1</span>



                                <?php



                                    }



                                }



                                ?>







                            </button>









                        <?php



                        } else if (getActiveUsers()->is_magaza == 2) {



                        ?>



                            <button onclick="git('<?= base_url(gg() . $magaza->link) ?>#content')" class="nav-link text-danger <?= ($uniq->id == 95) ? "active" : "" ?>">



                                <i class="feather-settings"></i><?= $magaza->titleh1 . (($_SESSION["lang"] == 1) ? " <small>Reddedildi</small>" : "<small> Rejected</small>") ?>



                            </button>



                            <?php



                        } else {



                            if (getActiveUsers()->magaza_name == "") {



                            ?>



                                <button onclick="git('<?= base_url(gg() . $magaza->link) ?>#content')" class="nav-link <?= ($uniq->id == 95) ? "active" : "" ?>">



                                    <i class="feather-settings"></i><?= $magaza->titleh1 ?>



                                </button>



                            <?php



                            } else {



                            ?>



                                <button onclick="git('<?= base_url(gg() . $magaza->link) ?>#content')" class="nav-link <?= ($uniq->id == 95) ? "active" : "" ?>">



                                    <i class="feather-settings"></i><?= $magaza->titleh1 ?>



                                    <script src="https://cdn.lordicon.com/bhenfmcm.js"></script>



                                    <lord-icon src="https://cdn.lordicon.com/kbtmbyzy.json" trigger="loop" colors="primary:white,secondary:#30e849" state="loop" style="width:20px;height:20px;padding-top:5px ">



                                    </lord-icon>



                                </button>











                        <?php



                            }



                        }



                        ?>

                        

                        <button onclick="git('<?= base_url(gg() . $yayinciPaneli->link) ?>#content')" class="nav-link <?= ($uniq->id == 122) ? "active" : "" ?>">



                            <img width="26px" style="margin-right: 10px;" src="<?= b() . "assets/img/live.png" ?>"><?= $yayinciPaneli->titleh1 ?>



                        </button>

                        <?php

                        $streamer = getTableSingle("streamer_users",array("user_id"=>getActiveUsers()->id,"status"=>1));

                        if($streamer):

                        ?>

                        

                        

                        <button onclick="git('<?= base_url(gg() . $bagisGecmisi->link) ?>#content')" class="nav-link <?= ($uniq->id == 124) ? "active" : "" ?>">



                            <img width="26px" style="margin-right: 10px;" src="<?= b() . "assets/img/icon/cash-on-delivery.png" ?>"><?= $bagisGecmisi->titleh1 ?>



                        </button>

                        <?php endif; ?>

                        

                        <button onclick="git('<?= base_url(gg() . $cekilisSistemi->link) ?>#content')" class="nav-link <?= ($uniq->id == 128) ? "active" : "" ?>">



                            <img width="26px" style="margin-right: 10px;" src="<?= b() . "upload/icon/open-box.png" ?>"><?= $cekilisSistemi->titleh1 ?>



                        </button>

                        <button onclick="git('<?= base_url(gg() . $referansSistemi->link) ?>#content')" class="nav-link <?= ($uniq->id == 129) ? "active" : "" ?>">



                            <img width="26px" style="margin-right: 10px;" src="<?= b() . "upload/icon/followers.png" ?>"><?= $referansSistemi->titleh1 ?>



                        </button>

                        <button onclick="git('<?= base_url(gg() . $ayarlar->link) ?>#content')" role="link" href="#" class="nav-link <?= ($uniq->id == 37) ? "active" : "" ?>">



                            <img width="26px" style="margin-right: 10px;" src="<?= b() . "assets/img/icon/settings.png" ?>"><?= $ayarlar->titleh1 ?>



                        </button>







                        <button onclick="git('<?= base_url(gg() . $bakiye->link) ?>#content')" role="link" class="nav-link <?= ($uniq->id == 28) ? "active" : "" ?>">



                            <img width="26px" style="margin-right: 10px;" src="<?= b() . "assets/img/moneys.png" ?>"><?= $bakiye->titleh1 ?>



                        </button>

                        <button onclick="git('<?= base_url(gg() . $bakiyeIade->link) ?>#content')" role="link" class="nav-link <?= ($uniq->id == 120) ? "active" : "" ?>">



                            <img width="26px" style="margin-right: 10px;" src="<?= b() . "assets/images/icom/wage.png" ?>"><?= $bakiyeIade->titleh1 ?>



                        </button>

                        

                        <button onclick="git('<?= base_url(gg() . $cekim->link) ?>#content')" role="link" class="nav-link <?= ($uniq->id == 51) ? "active" : "" ?>">



                            <img width="26px" style="margin-right: 10px;" src="<?= b() . "assets/img/icon/cash-on-delivery.png" ?>"><?= $cekim->titleh1 ?>



                        </button>

                        <button onclick="git('<?= base_url(gg() . $takip->link) ?>#content')" role="link" href="#" class="nav-link <?= ($uniq->id == 98) ? "active" : "" ?>">



                            <img width="26px" style="margin-right: 10px;" src="<?= b() . "upload/icon/followers.png" ?>"><?= $takip->titleh1 ?>



                        </button>



                        <button onclick="git('<?= base_url(gg() . $mesaj->link) ?>#content')" role="link" href="#" class="nav-link <?= ($uniq->id == 38) ? "active" : "" ?>">



                            <img width="26px" style="margin-right: 10px;" src="<?= b() . "assets/img/icon/chat.png" ?>"><?= $mesaj->titleh1 ?>



                        </button>



                        <button onclick="git('<?= base_url(gg() . $destek->link) ?>#content')" role="link" href="#" class="nav-link <?= ($uniq->id == 97) ? "active" : "" ?>">



                            <img width="26px" style="margin-right: 10px;" src="<?= b() . "assets/img/icon/support.png" ?>"><?= $destek->titleh1 ?>



                        </button>







                        <button onclick="git('<?= base_url(gg() . $bildirim->link) ?>#content')" role="link" href="#" class="nav-link <?= ($uniq->id == 78) ? "active" : "" ?>">



                            <img width="26px" style="margin-right: 10px;" src="<?= b() . "assets/img/icon/notification-bell.png" ?>"><?= $bildirim->titleh1 ?>



                        </button>



                        <button onclick="git('<?= base_url(gg() . $dogrulama->link) ?>#content')" role="link" href="#" class="nav-link <?= ($uniq->id == 42) ? "active" : "" ?>">



                            <img width="26px" style="margin-right: 10px;" src="<?= b() . "assets/images/icom/immigration.png" ?>"><?= $dogrulama->titleh1 ?>



                        </button>



                        <button onclick="git('<?= base_url(gg() . $sifre->link) ?>#content')" class="nav-link <?= ($uniq->id == 49) ? "active" : "" ?>">



                            <!-- https://feathericons.dev/?search=key&iconset=feather -->



                            <img src="<?= b() . "assets/img/reset-password.png" ?>" width="25px" style="margin-right: 10px" alt="">



                            <?= $sifre->titleh1 ?>



                        </button>



                        <button onclick="git('<?= base_url("exitt") ?>')" class="nav-link text-danger ">







                            <img src="<?= b() . "assets/images/icom/log-out.png" ?>" width="25px" style="margin-right: 10px" alt="">



                            <?= ($_SESSION["lang"] == 1) ? "Çıkış" : "Logout" ?>



                        </button>







                    </div>



                </nav>



                <!-- End tabs area -->



            </div>



            <div class="col-lg-10 col-md-9 col-sm-12 mt_sm--30">



                <div class="tab-content tab-content-edit-wrapepr" id="nav-tabContent">











                    <?php



                    if ($page->id == 99) {



                        $this->load->view($this->viewFolder . "/messages/detail/content");



                    } else {



                        $this->load->view($this->viewFolder . "/" . $this->uniqFolder . "/content");



                    }



                    ?>











                </div>







            </div>



        </div>



    </div>



</div>